apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-vertx-producer
  name: java-http-vertx-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-vertx-producer
  template:
    metadata:
      labels:
        app: java-http-vertx-producer
    spec:
      containers:
      - name: java-http-vertx-producer
        image: strimzi/java-http-vertx-producer:latest
        env:
          - name: HOSTNAME
            value: my-bridge-bridge-service
          - name: PORT
            value: "8080"
          - name: TOPIC
            value: my-topic
          - name: SEND_INTERVAL
            value: "1000"
          - name: JAEGER_SERVICE_NAME
            value: java-http-vertx-producer
          - name: JAEGER_AGENT_HOST
            value: my-jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-vertx-consumer
  name: java-http-vertx-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-vertx-consumer
  template:
    metadata:
      labels:
        app: java-http-vertx-consumer
    spec:
      containers:
      - name: java-http-vertx-consumer
        image: strimzi/java-http-vertx-consumer:latest
        env:
          - name: HOSTNAME
            value: my-bridge-bridge-service
          - name: PORT
            value: "8080"
          - name: TOPIC
            value: my-topic
          - name: GROUPID
            value: "my-group"
          - name: POLL_INTERVAL
            value: "1000"
          - name: JAEGER_SERVICE_NAME
            value: java-http-vertx-consumer
          - name: JAEGER_AGENT_HOST
            value: my-jaeger-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"